#!/usr/bin/env node
/**
 * Google Sign-In + Google Wallet provisioning helper (trainer-apps platform-api).
 *
 * Usage:
 *   cd platform-api
 *   export KK_TENANT_SLUG=kettle-kulture
 *   export KK_PUBLIC_SITE_ORIGIN=https://kettlekulture.co.uk
 *   node scripts/provision-google.mjs
 *
 * Writes .google-provision.local (gitignored) for push-google-to-railway.sh
 * Does NOT create GCP resources — follow printed checklist + docs/GOOGLE-PLATFORM-SETUP.md
 */
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const apiRoot = join(here, "..");
const outFile = join(apiRoot, ".google-provision.local");

const slug = process.env.KK_TENANT_SLUG || "kettle-kulture";
const origin = (process.env.KK_PUBLIC_SITE_ORIGIN || "https://kettlekulture.co.uk").replace(/\/$/, "");
const localOrigin = process.env.KK_LOCAL_ORIGIN || "http://localhost:3000";

const lines = [
  "# Generated by provision-google.mjs — push with ./scripts/push-google-to-railway.sh",
  `# Tenant: ${slug}`,
  "",
  "# --- Sign in with Google (OAuth Web client) ---",
  "# Create in Google Cloud → Auth Platform → Clients → Web application",
  `# Authorized JavaScript origins: ${origin}, ${localOrigin}`,
  "GOOGLE_CLIENT_ID=",
  "",
  "# --- Google Wallet (loyalty pass) ---",
  "# Enable API: Google Wallet API. Pay & Wallet Console → issuer ID + service account.",
  "GOOGLE_WALLET_ISSUER_ID=",
  `# One-line JSON from service account key (minified). Or set on Railway as secret.`,
  "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON=",
  `GOOGLE_WALLET_CLASS_SUFFIX=${slug.replace(/-/g, "_")}`,
  `GOOGLE_WALLET_ISSUER_NAME=${process.env.GOOGLE_WALLET_ISSUER_NAME || "Kettle Kulture"}`,
  `GOOGLE_WALLET_PROGRAM_NAME=${process.env.GOOGLE_WALLET_PROGRAM_NAME || "Membership"}`,
  `GOOGLE_WALLET_LOGO_URL=${origin}/favicon-512.png`,
  "GOOGLE_WALLET_BRAND_COLOR=#111111",
  `GOOGLE_WALLET_ORIGINS=${origin},${localOrigin}`,
  ""
];

if (existsSync(outFile)) {
  const existing = readFileSync(outFile, "utf8");
  for (const key of ["GOOGLE_CLIENT_ID", "GOOGLE_WALLET_ISSUER_ID", "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON"]) {
    const m = existing.match(new RegExp(`^${key}=(.*)$`, "m"));
    if (m && m[1].trim()) {
      const idx = lines.findIndex((l) => l.startsWith(`${key}=`));
      if (idx >= 0) lines[idx] = `${key}=${m[1].trim()}`;
    }
  }
}

writeFileSync(outFile, lines.join("\n"));

console.log(`
Google platform provisioning file: ${outFile}

CHECKLIST (once per GCP project — reuse for future client sites by adding origins):

1) OAuth consent + Web client (Sign in with Google)
   → ${origin}
   → ${localOrigin}
   Paste Client ID into GOOGLE_CLIENT_ID in ${outFile}

2) Enable "Google Wallet API" on the same GCP project

3) Google Pay & Wallet Console → create issuer → note Issuer ID
   → Service account with Wallet Object Issuer role
   → Download JSON key → minify into GOOGLE_WALLET_SERVICE_ACCOUNT_JSON

4) ./scripts/push-google-to-railway.sh && redeploy platform-api

5) Verify:
   curl -s $PLATFORM/v1/public/config | jq .googleSignInEnabled,.googleWalletEnabled

Full guide: docs/GOOGLE-PLATFORM-SETUP.md
Browser walkthrough: docs/GOOGLE-SIGN-IN-BROWSER-STEPS.md
`);
